version: '3.8'

services:
  polybot:
    image: ${IMG_NAME}
    env_file: .env
    ports:
      - "8443:8443"

  yoloservice:
    image: yourdockerhubusername/yoloservice-prod:latest
    ports:
      - "8081:8081"

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
    network_mode: host
