services:
  polybot:
    image: majedsaade/polybot_build_prod:latest
    container_name: polybot-prod
    env_file: .env
    ports:
      - "8443:8443"

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "8889:8889"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
    network_mode: host
