# .github/workflows/build-dev.yaml
name: Polybot Build Dev

on:
  push:
    branches:
      - dev
      - feature/dev_setup
      - feature/monitoring_dev_setup
      - feature/containerization
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        id: build
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          # Login to Docker Hub
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          
          # Create image name with run number
          IMG_NAME="$DOCKERHUB_USERNAME/polybot-dev:${{ github.run_number }}"
          echo "Building image: $IMG_NAME"
          
          # Build the Docker image
          docker build --build-arg ENVIRONMENT=development -t "$IMG_NAME" .
          
          # Push the image
          docker push "$IMG_NAME"
          
          # Output the image name for the next job
          echo "image=$IMG_NAME" >> $GITHUB_OUTPUT
          echo "Built and pushed image: $IMG_NAME"

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy-dev.yaml
    with:
      image: ${{ needs.Build.outputs.image }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      POLYBOT_EC2_HOST_DEV: ${{ secrets.POLYBOT_EC2_HOST_DEV }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      DISCORD_BOT_TOKEN_DEV: ${{ secrets.DISCORD_BOT_TOKEN_DEV }}