# .github/workflows/build-dev.yaml
name: Polybot Build Dev

on:
  push:
    branches:
      - dev
      - feature/dev_setup
      - feature/monitoring_dev_setup
      - feature/containerization
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and Push Docker Image
        id: build
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
          img_name="/polybot_build_dev:${{github.run_number}}"
          # same docker_image to pass it to the next workflow 
          echo "image=$img_name" >> "$GITHUB_OUTPUT"
          echo "Building Docker image: ${{ secrets.DOCKERHUB_USERNAME }}$img_name"
          # build & push the image 
          docker build --push -t "${{ secrets.DOCKERHUB_USERNAME }}$img_name"  
          
          echo "Successfully built and pushed: $img_name"

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy-dev.yaml
    with:
      image: ${{ needs.Build.outputs.image }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      POLYBOT_EC2_HOST_DEV: ${{ secrets.POLYBOT_EC2_HOST_DEV }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      DISCORD_BOT_TOKEN_DEV: ${{ secrets.DISCORD_BOT_TOKEN_DEV }}
