# .github/workflows/build-prod.yaml
name: Polybot Build Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and Push Docker Image
        id: build
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"

          img_name="$DOCKERHUB_USERNAME/polybot-prod:${{ github.run_number }}"
          echo "image=$img_name" >> $GITHUB_ENV
          echo "::set-output name=image::$img_name"

          docker build --build-arg ENVIRONMENT=production -t $img_name .
          docker push $img_name

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy-prod.yaml
    with:
      image: ${{ needs.Build.outputs.image }}
