name: Deploy Polybot

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REPO_URL: https://github.com/MajedSaade/PolybotService.git
  REPO_NAME: PolybotService

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.POLYBOT_EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config << EOF
          Host poly
              HostName $EC2_HOST
              User $EC2_USERNAME
              IdentityFile ~/.ssh/private_key
              StrictHostKeyChecking no
          EOF

      - name: Clone or Pull Code on EC2
        run: |
          ssh poly "if [ -d ~/PolybotServiceFursa ]; then cd ~/PolybotServiceFursa && git pull; else git clone ${REPO_URL} ~/PolybotServiceFursa; fi"

      - name: Run Deployment Script on EC2
        run: |
          ssh poly "cd ~/PolybotServiceFursa && bash deploy.sh"
