name: Deploy Polybot

on:
  push:
    branches:
      - main

jobs:
  DeployToEC2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo (for metadata only)
        uses: actions/checkout@v4

      - name: Deploy via SSH to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_IP: ${{ secrets.POLYBOT_EC2_IP }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_IP '
            set -e  # Exit on error
            REPO_DIR="MyPolyBot"

            if [ -d "$REPO_DIR" ]; then
              echo "✅ Pulling latest code..."
              cd "$REPO_DIR"
              git pull
            else
              echo "📦 Cloning repository..."
              git clone https://github.com/${{ github.repository }}.git "$REPO_DIR"
              cd "$REPO_DIR"
            fi

            echo "📁 Setting up virtual environment..."
            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            fi

            source .venv/bin/activate
            pip install --upgrade pip
            pip install -r polybot/requirements.txt

            echo "🛠️ Updating polybot.service..."
            sudo cp polybot.service /etc/systemd/system/polybot.service
            sudo systemctl daemon-reload
            sudo systemctl restart polybot.service
            echo "🚀 Polybot service restarted."
          '
