name: Polybot Deploy Dev

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      EC2_SSH_KEY:
        required: true
      POLYBOT_EC2_HOST_DEV:
        required: true
      EC2_USERNAME:
        required: true
      DISCORD_BOT_TOKEN_DEV:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.POLYBOT_EC2_HOST_DEV }} >> ~/.ssh/known_hosts

      - name: Copy deployment files
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.POLYBOT_EC2_HOST_DEV }} "mkdir -p ~/polybot-deploy"
          scp -i ~/.ssh/id_rsa docker-compose.dev.yaml ${{ secrets.EC2_USERNAME }}@${{ secrets.POLYBOT_EC2_HOST_DEV }}:~/polybot-deploy/docker-compose.yml
          scp -i ~/.ssh/id_rsa otel-collector-config.yaml ${{ secrets.EC2_USERNAME }}@${{ secrets.POLYBOT_EC2_HOST_DEV }}:~/polybot-deploy/otel-collector-config.yaml

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.POLYBOT_EC2_HOST_DEV }} << EOF
            set -e

            # Install Docker and Compose plugin
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io docker-compose-plugin
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker \$USER
            fi

            cd ~/polybot-deploy

            # Create .env file safely
            printf '%s\n' \
            "IMG_NAME=${IMG_NAME}" \
            "ENVIRONMENT=development" \
            "DISCORD_DEV_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN_DEV }}" \
            "AWS_DEV_S3_BUCKET=majed-dev-bucket" \
            "AWS_REGION=us-west-2" \
            "YOLO_URL=http://10.0.0.66:8081/predict" \
            "OLLAMA_URL=http://10.0.0.136:11434/api/chat" \
            "STATUS_SERVER_PORT=8443" > .env

            # Login to Docker Hub
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # Stop and remove old containers
            sudo docker compose down --remove-orphans || true
            sudo docker rm -f polybot-deploy-otelcol-1 || true

            # Pull and start containers
            sudo docker compose --env-file .env pull
            sudo docker compose --env-file .env up -d

            # Cleanup old images
            sudo docker image prune -f
            echo "✅ Deployment completed!"
            EOF
