name: Test and Deploy Polybot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_IP: ${{ secrets.POLYBOT_EC2_IP }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_IP '
            REPO_DIR="/home/ubuntu/MyPolyBot"
            
            if [ -d "$REPO_DIR" ]; then
              echo "Directory $REPO_DIR exists. Pulling latest changes..."
              cd "$REPO_DIR"
              git pull
            else
              echo "Cloning repository into $REPO_DIR..."
              git clone https://github.com/${{ github.repository }}.git "$REPO_DIR"   
              cd "$REPO_DIR"
            fi
      
            echo "Installing and restarting polybot service..."
            
            # Create virtual environment if it doesn't exist
            if [ ! -d ".venv" ]; then
              echo "Creating Python virtual environment..."
              python3 -m venv .venv
            fi
          
            # Activate virtual environment and install requirements
            source .venv/bin/activate
            pip install -r polybot/requirements.txt
            
            # Deploy service
            sudo cp polybot.service /etc/systemd/system/
            sudo systemctl daemon-reload
            sudo systemctl restart polybot.service
            sudo systemctl enable polybot.service
            
            # Check if service is running
            if ! systemctl is-active --quiet polybot.service; then
              echo "❌ polybot.service is not running."
              sudo systemctl status polybot.service --no-pager
              exit 1
            fi
            
            echo "✅ polybot.service deployed and running."
          '