name: Deploy Polybot (Dev)
# majed-dev_test233456

on:
  push:
    branches:
      - dev
      - feature/dev_setup
  workflow_dispatch:

env:
  REPO_URL: https://github.com/MajedSaade/MyPolyBot.git
  REPO_NAME: MyPolyBot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH for Dev
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.POLYBOT_EC2_HOST_DEV }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config << EOF
          Host polydev
            HostName $EC2_HOST
            User $EC2_USERNAME
            IdentityFile ~/.ssh/private_key
            StrictHostKeyChecking no
          EOF

      - name: Clone or Pull Code on Dev EC2
        run: |
          # Get the current branch name that triggered the workflow
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Deploying from branch: $BRANCH_NAME"
          
          ssh polydev "if [ -d ~/${REPO_NAME} ]; then
                        cd ~/${REPO_NAME} && git fetch origin && git checkout $BRANCH_NAME && git pull origin $BRANCH_NAME;
                      else
                        git clone --branch $BRANCH_NAME ${REPO_URL} ~/${REPO_NAME};
                      fi"

      - name: Run Deployment Script on Dev EC2
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN_DEV }}
        run: |
          ssh polydev "cd ~/${REPO_NAME} && DISCORD_BOT_TOKEN='$DISCORD_BOT_TOKEN' bash deploy-dev.sh"
