name: Docker Scout Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  docker-scout:
    name: Run Docker Scout Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write  # Needed to post PR comments

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Scout CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Build the Docker image
        run: |
          docker build -t polybot:pr-${{ github.event.pull_request.number }} .

      - name: Run Docker Scout scan using policy
        id: scan
        run: |
          docker scout scan polybot:pr-${{ github.event.pull_request.number }} \
            --policy .docker/scout-policy.json \
            --format markdown > scout_report.md

          if grep -q "non-compliant" scout_report.md; then
            echo "❌ Policy violations found. Failing PR."
            cat scout_report.md
            exit 1
          else
            echo "✅ Passed Docker Scout policy check."
          fi

      - name: Post scan results as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: scout_report.md
