name: Project auto-testing

on:
  push:
    branches:
      - main
      - feature/**

permissions: {}

jobs:
  TestImgProcessingChatbotApp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install matplotlib
          pip install -r polybot/requirements.txt

      - name: Test Filters
        run: |
          source venv/bin/activate
          echo -e "\n✅ Testing concat()"
          python -m polybot.test.test_concat

          echo -e "\n✅ Testing rotate()"
          python -m polybot.test.test_rotate

          echo -e "\n✅ Testing salt_n_pepper()"
          python -m polybot.test.test_salt_n_pepper

          echo -e "\n✅ Testing segment()"
          python -m polybot.test.test_segment

      - name: Test Discord Bot
        run: |
          source venv/bin/activate
          echo -e "\n✅ Testing Discord Bot"
          python -m polybot.test.test_discord_bot
